[package]
name = "frps"
version = "0.1.3"
edition = "2021"

[dependencies]
frp-core = { path = "../frp-core" }
frp-server = { path = "../frp-server" }
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
toml.workspace = true
serde.workspace = true

[[bin]]
name = "frps"
path = "src/main.rs"
