[workspace]
resolver = "2"
members = [
    "frp-core",
    "frp-server",
    "frp-client",
    "frps",
    "frpc",
]

[workspace.dependencies]
tokio = { version = "1", default-features = false, features = ["net", "io-util", "time", "sync", "macros", "signal", "rt-multi-thread"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
anyhow = "1"
tracing = "0.1"
thiserror = "2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
bytes = "1"
uuid = { version = "1", features = ["v4"] }
tokio-tungstenite = "0.24"
sha2 = "0.10"
sha1 = "0.10"
md-5 = "0.10"
hmac = "0.12"
hex = "0.4"
data-encoding = "2"
aes = "0.8"
cfb-mode = "0.8"
pbkdf2 = "0.12"
snap = "1"
rand = "0.8"
flate2 = "1.0"
tokio-rustls = { version = "0.26", default-features = false }
rustls = { version = "0.23", default-features = false, features = ["ring", "tls12"] }
rustls-pemfile = "2"
futures-util = "0.3"
webpki-roots = "0.26"
axum = "0.8.9"
libc = "0.2"
yamux = "0.14"
tokio-util = { version = "0.7", features = ["compat"] }

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
strip = "symbols"
panic = "abort"
