[package]
name = "frp-core"
version = "0.3.2"
edition = "2021"

[dependencies]
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
bpaf.workspace = true
toml.workspace = true
anyhow.workspace = true
tracing.workspace = true
thiserror.workspace = true
bytes.workspace = true
axum = { workspace = true, optional = true }
uuid.workspace = true
tokio-tungstenite = { workspace = true, optional = true }
sha1.workspace = true
md-5.workspace = true
hex.workspace = true
data-encoding.workspace = true
aes.workspace = true
cfb-mode.workspace = true
pbkdf2.workspace = true
snap = { workspace = true, optional = true }
rand.workspace = true
futures-util.workspace = true
tokio-rustls = { workspace = true, optional = true }
rustls = { workspace = true, optional = true }
rustls-pemfile = { workspace = true, optional = true }
rustls-platform-verifier = { workspace = true, optional = true }
ring = { workspace = true }
yamux = { workspace = true, optional = true }
tokio-util.workspace = true
kcp = { workspace = true, optional = true }
quinn = { workspace = true, optional = true }

socket2.workspace = true
jsonwebtoken = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true }
chacha20poly1305 = { workspace = true, optional = true }
rcgen = { version = "0.13", optional = true, default-features = false, features = ["ring"] }

[features]
default = ["quic", "kcp", "websocket", "oidc", "tls", "compression", "chacha20", "vnet", "tcp-mux"]
tcp-mux = ["dep:yamux"]
tls = ["dep:rustls", "dep:tokio-rustls", "dep:rustls-pemfile", "dep:rustls-platform-verifier", "dep:rcgen"]
admin-auth = ["dep:axum"]
compression = ["dep:snap"]
chacha20 = ["dep:chacha20poly1305"]
quic = ["dep:quinn", "tls"]
kcp = ["dep:kcp"]
websocket = ["dep:tokio-tungstenite"]
oidc = ["dep:jsonwebtoken", "dep:reqwest"]
vnet = []


[dev-dependencies]
tower = "0.5"
criterion.workspace = true
proptest = "1.6"

[[bench]]
name = "crypto_bridge"
harness = false
