[package]
name = "frp-client"
version = "0.1.6"
edition = "2021"

[dev-dependencies]
frp-server = { path = "../frp-server" }
tracing-subscriber.workspace = true

[dependencies]
frp-core = { path = "../frp-core" }
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
tracing.workspace = true
thiserror.workspace = true
uuid.workspace = true
tokio-tungstenite.workspace = true
