#!/usr/bin/env bash
# docs-go-column.sh — fixture checks for the `Go frp Equivalent` column of docs/config.md.
#
# Why this exists: docs/config.md's opening paragraph used to claim "Every field maps 1:1 to a
# Go frp v0.71.0 equivalent", but nothing measured that column. Two rows had already rotted by
# hand: PR #448 fixed a row naming a Go spelling `frps` does not accept, and PR #455 found a
# second row naming a Go field `frps` does not read. A reader who trusts the column cannot tell
# a mapped row from a divergence, and a wrong spelling is invisible to every other guard in the
# tree.
#
# What the gate measures (the four M-1 Go-column residues this round closes)
#   membership   every Go cell that names a key must appear in `GO`, the 261-spelling accept
#                set; anything else must be a recorded divergence marker or a documented
#                non-token shape.
#   the key set  `GO` is no longer trusted. `scripts/tests/docs-go-column-go-keys.txt` records
#                the same set as a derivation artifact (one spelling per line, sorted, with its
#                provenance) and the scan diffs the embedded table against it, so a
#                transcription error in either reds. The artifact is regenerated by
#                `scripts/tests/docs-go-column-derive-go-keys.sh` (`--fetch`, or `--source DIR`
#                for a local checkout); that script skips cleanly (SKIP, exit 0) when no source
#                is available, and the gate itself never needs the Go source.
#   the mapping  every data row is keyed `(table ordinal, field)` in `ROW_GO_PATHS` with the Go
#                cell it must carry — a `json` path, a qualified path plus shape, a divergence
#                marker, an extension marker naming the absent spelling, or a documented
#                non-token shape. A cell holding another real Go key (the recorded
#                falsification was `bindPort` -> `quicBindPort`) is a violation, not a pass.
#   the aliases  the 41 doc spellings the M-1 round recorded in `ALIASES` are resolved in
#                `ALIAS_RESOLUTION`: each is either repointed to the Go path it should have
#                named (checked against `GO` and against the row's recorded cell) or recorded
#                in docs/config.md as an extension whose absent spelling the marker names and
#                the recorded key set proves absent. `ALIASES` itself is now empty — no
#                accepted alias remains — but the mechanism stays, so a new one has to be
#                recorded here (and the inventory reds on an unused entry).
#
# Provenance of the recorded key set
#   Go frp v0.71.0. The annotated tag `v0.71.0` is object 40adeed73b51e7ee1766d7cfb15d02ba9431ba2b,
#   which points at commit 4a23aa181c1d7e28eecaa8216024ed753b9d27c8.
#   Source files read: pkg/config/v1/{server,client,common,proxy,visitor,proxy_plugin,
#   visitor_plugin,value_source,api,store,decode}.go.
#   `pkg/config/v1/decode.go` carries no alias or legacy table — it dispatches on the `type` key
#   straight into `jsonx.UnmarshalWithOptions` — so Go accepts only the exact `json:"..."` spellings.
#   Accept set = every dotted `json` path reachable from `ServerConfig`, `ClientConfig` and the
#   `*ProxyConfig` / `*VisitorConfig` / `*PluginOptions` structs (embedded structs followed,
#   `json:"-"` ignored), plus every bare `json` field name in the `pkg/config/v1` config structs:
#   108 dotted paths + 153 bare names = 261 distinct spellings (the two sets are disjoint).
#   Re-derive and diff the artifact:
#     bash scripts/tests/docs-go-column-derive-go-keys.sh --fetch --check
#
# A data row passes when its Go cell is
#   go         the `json` path `ROW_GO_PATHS` records for that row, and that path is in `GO`
#   qualified  `` `tok` (start|end|nested) `` with `tok` the recorded Go frp v0.71.0 spelling
#   divergent  the recorded em-dash divergence marker (`—`, `` `—` ``, optionally with prose)
#   extension  an em-dash marker naming a spelling the recorded key set proves Go does not have
#   nontoken   one of the four documented non-token shapes: `**Required.**`,
#              `` `sk` / `secretKey` ``, `` `transport.wireProtocol = "v2"` ``
#   alias      a spelling in the accepted `ALIASES` table (currently empty)
# Anything else is a violation. The `ALIASES` table is the recorded exemption for spellings a
# human has not yet resolved, and the fixture names each one's divergence in the
# failure/success message rather than hiding it.
#
# The two rows that name a Go spelling `frps` does not read are additionally pinned by line,
# field name and prose (`websocket_port` at docs/config.md:22, `tls_enable` at docs/config.md:25),
# so re-wording either back into a bare Go spelling reds even if someone later adds that spelling
# to `ALIASES` or to `GO`.
#
# The inventory counts are deliberate: a table appearing, a row being added, or a Go cell
# changing has to be recorded here in the same commit instead of passing silently.
#
# Scenarios
#   1  the row-by-row scan of `$DOCS_CONFIG` (default docs/config.md): 17 Go-column tables,
#      192 data rows, 24 divergence markers, 0 alias rows, the key-set artifact diff, the 41
#      alias resolutions, one check per data row and one per pinned row.
#   2  seven mutations of a copy of the repository's own docs/config.md, each of which must red —
#      M1 reword the `websocket_port` divergence to `websocketPort`, M2 reword `tls_enable` to
#      `tlsEnable`, M3 misspell a curated token (`bindAddr` -> `bindAddress`), M4 drop every
#      table, M5 strip the `websocket_port` divergence prose, M6 swap a real Go key into the
#      wrong row (`bindPort` -> `quicBindPort`), M7 substitute a spelling Go does not carry
#      (`bindPort` -> `kcpPort`). A green suite on any mutant would mean the fixture does not
#      drive the scan it claims to.
#
# Usage: bash scripts/tests/docs-go-column.sh
#        DOCS_CONFIG=/tmp/mutated-config.md bash scripts/tests/docs-go-column.sh
# `DOCS_CONFIG` points the scenario-1 scan at a mutated copy; the scenario-2 mutations are always
# taken from the repository's own docs/config.md, so the seam cannot switch them off.
set -uo pipefail

# --- self-defence: assert a floor on every exit path --------------------------
# A suite that silently stops checking must not exit green. The trap is installed before the path
# resolution and the first check, so an early `exit 0` anywhere below it still has to answer to the
# floor. `MIN_CHECKS` is the measured check count of a green run.
MIN_CHECKS=257
checks=0
fails=0
WORK=""

# shellcheck disable=SC2329  # invoked by the EXIT trap below, not directly
cleanup() {
  local rc=$?
  if [ -n "$WORK" ] && [ -d "$WORK" ]; then
    rm -rf "$WORK"
  fi
  if [ "$rc" -eq 0 ] && [ "$checks" -lt "$MIN_CHECKS" ]; then
    printf 'docs-go-column: only %d check(s) ran, floor %d — the suite was cut short\n' \
      "$checks" "$MIN_CHECKS" >&2
    exit 1
  fi
  exit "$rc"
}
trap cleanup EXIT

ok() {
  checks=$((checks + 1))
  printf '  ok    %s\n' "$1"
}

bad() {
  checks=$((checks + 1))
  fails=$((fails + 1))
  printf '  FAIL  %s\n' "$1"
}

# --- locate the repository even through a symlink -----------------------------
SOURCE="${BASH_SOURCE[0]}"
while [ -L "$SOURCE" ]; do
  DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
  SOURCE="$(readlink "$SOURCE")"
  case "$SOURCE" in
    /*) ;;
    *) SOURCE="$DIR/$SOURCE" ;;
  esac
done
SCRIPT_DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
PRISTINE="$REPO_ROOT/docs/config.md"

DOCS_CONFIG="${DOCS_CONFIG:-docs/config.md}"
case "$DOCS_CONFIG" in
  /*) ;;
  *) DOCS_CONFIG="$REPO_ROOT/$DOCS_CONFIG" ;;
esac

if [ ! -f "$PRISTINE" ]; then
  printf 'FAIL  cannot locate docs/config.md from %s\n' "$SCRIPT_DIR" >&2
  exit 1
fi
if [ ! -f "$DOCS_CONFIG" ]; then
  printf 'FAIL  cannot read DOCS_CONFIG=%s\n' "$DOCS_CONFIG" >&2
  exit 1
fi
if ! command -v python3 >/dev/null 2>&1; then
  printf 'FAIL  python3 not found — the Go frp equivalent column cannot be scanned\n' >&2
  exit 1
fi

WORK="$(mktemp -d)"

# --- the scan: one `ok`/`bad` line per check, ordered -------------------------
# Emitted messages already carry the canonical `docs/config.md:<line>` label, so a scan of a
# mutated copy still names the row it is talking about rather than the copy's temporary path.
scan() { # <doc> ; the recorded key artifact is resolved from the script's own root
  python3 -B - "$1" "$REPO_ROOT/scripts/tests/docs-go-column-go-keys.txt" <<'PY'
import re
import sys

HDR = "| Field | Type | Default | Go frp Equivalent | Description |"
GO_ARTIFACT = sys.argv[2]
EXPECTED_TABLES = 17
EXPECTED_ROWS = 192
EXPECTED_DIVERGENT = 24
EXPECTED_ALIAS_ROWS = 0
EXPECTED_GO_KEYS = 261
EXPECTED_GO_DOTTED = 108
EXPECTED_GO_BARE = 153
EXPECTED_ROW_PATHS = 192
EXPECTED_RESOLUTIONS = 41

# --- curated Go frp v0.71.0 spellings: dotted json paths + bare json field names ---
GO = {
    "additionalEndpointParams",
    "additionalScopes",
    "addr",
    "address",
    "allowPorts",
    "allowUsers",
    "annotations",
    "args",
    "assetsDir",
    "audience",
    "auth",
    "auth.additionalScopes",
    "auth.method",
    "auth.oidc",
    "auth.oidc.additionalEndpointParams",
    "auth.oidc.audience",
    "auth.oidc.clientID",
    "auth.oidc.clientSecret",
    "auth.oidc.insecureSkipVerify",
    "auth.oidc.issuer",
    "auth.oidc.proxyURL",
    "auth.oidc.scope",
    "auth.oidc.skipExpiryCheck",
    "auth.oidc.skipIssuerCheck",
    "auth.oidc.tokenEndpointURL",
    "auth.oidc.tokenSource",
    "auth.oidc.tokenSource.exec",
    "auth.oidc.tokenSource.exec.args",
    "auth.oidc.tokenSource.exec.command",
    "auth.oidc.tokenSource.exec.env",
    "auth.oidc.tokenSource.exec.env.name",
    "auth.oidc.tokenSource.exec.env.value",
    "auth.oidc.tokenSource.file",
    "auth.oidc.tokenSource.file.path",
    "auth.oidc.tokenSource.type",
    "auth.oidc.trustedCaFile",
    "auth.token",
    "auth.tokenSource",
    "auth.tokenSource.exec",
    "auth.tokenSource.exec.args",
    "auth.tokenSource.exec.command",
    "auth.tokenSource.exec.env",
    "auth.tokenSource.exec.env.name",
    "auth.tokenSource.exec.env.value",
    "auth.tokenSource.file",
    "auth.tokenSource.file.path",
    "auth.tokenSource.type",
    "authorizedKeysFile",
    "autoGenPrivateKeyPath",
    "bandwidthLimit",
    "bandwidthLimitMode",
    "bindAddr",
    "bindPort",
    "certFile",
    "clientID",
    "clientSecret",
    "command",
    "connectServerLocalIP",
    "crtPath",
    "custom404Page",
    "customDomains",
    "destinationIP",
    "detailedErrorsToClient",
    "dialServerKeepalive",
    "dialServerTimeout",
    "disableAssistedAddrs",
    "disableCustomTLSFirstByte",
    "disablePrintColor",
    "dnsServer",
    "enable",
    "enableHTTP2",
    "enablePrometheus",
    "enabled",
    "env",
    "exec",
    "fallbackTimeoutMs",
    "fallbackTo",
    "featureGates",
    "file",
    "force",
    "group",
    "groupKey",
    "healthCheck",
    "healthCheck.httpHeaders",
    "healthCheck.httpHeaders.name",
    "healthCheck.httpHeaders.value",
    "healthCheck.intervalSeconds",
    "healthCheck.maxFailed",
    "healthCheck.path",
    "healthCheck.timeoutSeconds",
    "healthCheck.type",
    "heartbeatInterval",
    "heartbeatTimeout",
    "hostHeaderRewrite",
    "httpHeaders",
    "httpPassword",
    "httpPlugins",
    "httpPlugins.addr",
    "httpPlugins.name",
    "httpPlugins.ops",
    "httpPlugins.path",
    "httpPlugins.tlsVerify",
    "httpUser",
    "includes",
    "insecureSkipVerify",
    "intervalSeconds",
    "issuer",
    "kcpBindPort",
    "keepTunnelOpen",
    "keepalivePeriod",
    "keyFile",
    "keyPath",
    "level",
    "loadBalancer",
    "loadBalancer.group",
    "loadBalancer.groupKey",
    "localAddr",
    "localIP",
    "localPath",
    "localPort",
    "locations",
    "log",
    "log.disablePrintColor",
    "log.level",
    "log.maxDays",
    "log.to",
    "loginFailExit",
    "maxDays",
    "maxFailed",
    "maxIdleTimeout",
    "maxIncomingStreams",
    "maxPoolCount",
    "maxPortsPerClient",
    "maxRetriesAnHour",
    "metadatas",
    "method",
    "minRetryInterval",
    "multiplexer",
    "name",
    "natHoleStunServer",
    "natTraversal",
    "natTraversal.disableAssistedAddrs",
    "natholeAnalysisDataReserveHours",
    "oidc",
    "ops",
    "password",
    "path",
    "plugin",
    "plugin.type",
    "poolCount",
    "port",
    "pprofEnable",
    "privateKeyFile",
    "protocol",
    "proxies",
    "proxies.type",
    "proxyBindAddr",
    "proxyProtocolVersion",
    "proxyURL",
    "quic",
    "quicBindPort",
    "remotePort",
    "requestHeaders",
    "requestHeaders.set",
    "responseHeaders",
    "responseHeaders.set",
    "routeByHTTPUser",
    "scope",
    "secretKey",
    "serverAddr",
    "serverName",
    "serverPort",
    "serverUser",
    "set",
    "skipExpiryCheck",
    "skipIssuerCheck",
    "sshTunnelGateway",
    "sshTunnelGateway.authorizedKeysFile",
    "sshTunnelGateway.autoGenPrivateKeyPath",
    "sshTunnelGateway.bindPort",
    "sshTunnelGateway.privateKeyFile",
    "start",
    "store",
    "store.path",
    "stripPrefix",
    "subDomainHost",
    "subdomain",
    "tcpKeepalive",
    "tcpMux",
    "tcpMuxKeepaliveInterval",
    "tcpmuxHTTPConnectPort",
    "tcpmuxPassthrough",
    "timeoutSeconds",
    "tls",
    "tlsVerify",
    "to",
    "token",
    "tokenEndpointURL",
    "tokenSource",
    "transport",
    "transport.bandwidthLimit",
    "transport.bandwidthLimitMode",
    "transport.connectServerLocalIP",
    "transport.dialServerKeepalive",
    "transport.dialServerTimeout",
    "transport.heartbeatInterval",
    "transport.heartbeatTimeout",
    "transport.maxPoolCount",
    "transport.poolCount",
    "transport.protocol",
    "transport.proxyProtocolVersion",
    "transport.proxyURL",
    "transport.quic",
    "transport.quic.keepalivePeriod",
    "transport.quic.maxIdleTimeout",
    "transport.quic.maxIncomingStreams",
    "transport.tcpKeepalive",
    "transport.tcpMux",
    "transport.tcpMuxKeepaliveInterval",
    "transport.tls",
    "transport.tls.certFile",
    "transport.tls.disableCustomTLSFirstByte",
    "transport.tls.enable",
    "transport.tls.force",
    "transport.tls.keyFile",
    "transport.tls.serverName",
    "transport.tls.trustedCaFile",
    "transport.useCompression",
    "transport.useEncryption",
    "transport.wireProtocol",
    "trustedCaFile",
    "type",
    "udpPacketSize",
    "unixPath",
    "useCompression",
    "useEncryption",
    "user",
    "userConnTimeout",
    "username",
    "value",
    "version",
    "vhostHTTPPort",
    "vhostHTTPSPort",
    "vhostHTTPTimeout",
    "virtualNet",
    "virtualNet.address",
    "visitors",
    "visitors.type",
    "webServer",
    "webServer.addr",
    "webServer.assetsDir",
    "webServer.password",
    "webServer.port",
    "webServer.pprofEnable",
    "webServer.tls",
    "webServer.tls.certFile",
    "webServer.tls.keyFile",
    "webServer.tls.serverName",
    "webServer.tls.trustedCaFile",
    "webServer.user",
    "wireProtocol",
}

# --- accepted doc spellings that are NOT Go frp v0.71.0 json keys -------------------
# Empty by design: the M-1 round recorded 41 of these, and the M-1 residue asked for every
# one of them to be repointed to its true Go path or recorded in docs/config.md as an extension.
# Both happened (see `ALIAS_RESOLUTION` below and the markers in the document), so no accepted
# alias is left. The mechanism stays: an entry added here has to be used by a row, and a row
# carrying an unrecorded spelling still reds as a violation.
ALIASES = {}

# --- the 41 recorded aliases, resolved ----------------------------------------------
# old doc spelling -> 'repoint:<the Go v0.71.0 json path it should have named>'
#                  |  'extension'
# `repoint` means the field does have a Go key and the document now names it (the path must be
# in `GO` and the row's expected cell in `ROW_GO_PATHS`); `extension` means no Go v0.71.0 json
# key carries that name at all, and the document records a divergence marker naming the absent
# spelling. Both halves are checked mechanically against the recorded key set.
ALIAS_RESOLUTION = {
    'auth.additionalAuthScopes': 'repoint:auth.additionalScopes',
    'auth.additionalEndpointParams': 'repoint:auth.oidc.additionalEndpointParams',
    'auth.authenticationTimeout': 'extension',
    'auth.insecureSkipVerify': 'repoint:auth.oidc.insecureSkipVerify',
    'auth.oidcAdditionalAudience': 'extension',
    'auth.oidcAudience': 'repoint:auth.oidc.audience',
    'auth.oidcClientId': 'repoint:auth.oidc.clientID',
    'auth.oidcClientSecret': 'repoint:auth.oidc.clientSecret',
    'auth.oidcIssuer': 'repoint:auth.oidc.issuer',
    'auth.oidcProxyURL': 'repoint:auth.oidc.proxyURL',
    'auth.oidcScope': 'repoint:auth.oidc.scope',
    'auth.oidcSkipAudience': 'extension',
    'auth.oidcSkipExpiry': 'repoint:auth.oidc.skipExpiryCheck',
    'auth.oidcSkipIssuer': 'repoint:auth.oidc.skipIssuerCheck',
    'auth.oidcSkipNbf': 'extension',
    'auth.oidcTLSTrustedCAFile': 'repoint:auth.oidc.trustedCaFile',
    'auth.oidcTokenEndpoint': 'repoint:auth.oidc.tokenEndpointURL',
    'auth.oidcTokenSource': 'repoint:auth.oidc.tokenSource',
    'auth.tlsTrustedCaFile': 'repoint:auth.oidc.trustedCaFile',
    'auth.tokenAuthTimeout': 'extension',
    'clientId': 'repoint:clientID',
    'enableControl': 'extension',
    'headers': 'extension',
    'httpPwd': 'repoint:httpPassword',
    'localIp': 'repoint:localIP',
    'maxConnsPerProxy': 'extension',
    'maxProxiesPerClient': 'extension',
    'metas': 'repoint:metadatas',
    'pluginCrtPath': 'repoint:crtPath',
    'pluginKeyPath': 'repoint:keyPath',
    'sk': 'repoint:secretKey',
    'sshTunnelGateway.bindAddr': 'extension',
    'sudpPort': 'extension',
    'tcpMuxPassthrough': 'repoint:tcpmuxPassthrough',
    'timeout': 'extension',
    'tlsServerName': 'repoint:transport.tls.serverName',
    'url': 'extension',
    'webServer.custom404Page': 'repoint:custom404Page',
    'webServer.enablePrometheus': 'repoint:enablePrometheus',
    'webServer.tlsCertFile': 'repoint:webServer.tls.certFile',
    'webServer.tlsKeyFile': 'repoint:webServer.tls.keyFile',
}

# --- the Go cell each data row must carry -------------------------------------------
# Keyed by `(table ordinal, field)`; the ordinal is the row's Go-column table in document
# order, stable under line shifts. Expectation forms:
#   'go:<json path>'          the cell must be exactly `` `<path>` ``, and <path> must be in GO
#   'qualified:<path>:<shape>' the cell must be `` `<path>` (start|end|nested) ``
#   'divergent'               the cell must be the recorded em-dash marker
#   'extension:<spelling>'    the marker must name <spelling> and GO must not carry it
#   'nontoken:<shape>'        the cell must be that documented non-token shape
# A row with no entry here, and an entry whose row is gone, both red. This is the recorded
# mapping assertion: it makes a single-sided edit to the document (or to this table) visible,
# while every path it records is additionally required to exist in the re-derived key set.
ROW_GO_PATHS = {
    # table 1
    (1, 'bind_addr'): 'go:bindAddr',
    (1, 'bind_port'): 'go:bindPort',
    (1, 'proxy_bind_addr'): 'go:proxyBindAddr',
    (1, 'vhost_http_port'): 'go:vhostHTTPPort',
    (1, 'vhost_https_port'): 'go:vhostHTTPSPort',
    (1, 'tcpmux_httpconnect_port'): 'go:tcpmuxHTTPConnectPort',
    (1, 'kcp_bind_port'): 'go:kcpBindPort',
    (1, 'quic_bind_port'): 'go:quicBindPort',
    (1, 'websocket_port'): 'divergent',
    (1, 'sudp_port'): 'extension:sudpPort',
    (1, 'sub_domain_host'): 'go:subDomainHost',
    (1, 'tls_enable'): 'divergent',
    (1, 'tls_only'): 'go:transport.tls.force',
    (1, 'tls_cert_file'): 'go:transport.tls.certFile',
    (1, 'tls_key_file'): 'go:transport.tls.keyFile',
    (1, 'tls_ca_file'): 'go:transport.tls.trustedCaFile',
    (1, 'allow_port_start'): 'qualified:allowPorts:start',
    (1, 'allow_port_end'): 'qualified:allowPorts:end',
    (1, 'allow_ports'): 'go:allowPorts',
    (1, 'max_ports_per_client'): 'go:maxPortsPerClient',
    (1, 'max_conns_per_proxy'): 'extension:maxConnsPerProxy',
    (1, 'max_proxies_per_client'): 'extension:maxProxiesPerClient',
    (1, 'vhost_http_timeout'): 'go:vhostHTTPTimeout',
    (1, 'user_conn_timeout'): 'go:userConnTimeout',
    (1, 'detailed_errors_to_client'): 'go:detailedErrorsToClient',
    (1, 'tcp_mux_passthrough'): 'go:tcpmuxPassthrough',
    (1, 'udp_packet_size'): 'go:udpPacketSize',
    (1, 'nat_hole_analysis_data_reserve_hours'): 'go:natholeAnalysisDataReserveHours',
    (1, 'includes'): 'go:includes',
    # table 2
    (2, 'method'): 'go:auth.method',
    (2, 'token'): 'go:auth.token',
    (2, 'token_source'): 'go:auth.tokenSource',
    (2, 'oidc_issuer'): 'go:auth.oidc.issuer',
    (2, 'oidc_audience'): 'go:auth.oidc.audience',
    (2, 'oidc_token_endpoint'): 'go:auth.oidc.tokenEndpointURL',
    (2, 'oidc_skip_expiry'): 'go:auth.oidc.skipExpiryCheck',
    (2, 'oidc_skip_issuer'): 'go:auth.oidc.skipIssuerCheck',
    (2, 'oidc_skip_audience'): 'extension:auth.oidcSkipAudience',
    (2, 'oidc_additional_audience'): 'extension:auth.oidcAdditionalAudience',
    (2, 'oidc_tls_trusted_ca_file'): 'go:auth.oidc.trustedCaFile',
    (2, 'oidc_proxy_url'): 'go:auth.oidc.proxyURL',
    (2, 'oidc_skip_nbf'): 'extension:auth.oidcSkipNbf',
    (2, 'authentication_timeout'): 'extension:auth.authenticationTimeout',
    (2, 'token_auth_timeout'): 'extension:auth.tokenAuthTimeout',
    (2, 'additional_auth_scopes'): 'go:auth.additionalScopes',
    # table 3
    (3, 'level'): 'go:log.level',
    (3, 'file'): 'go:log.to',
    (3, 'max_days'): 'go:log.maxDays',
    (3, 'format'): 'divergent',
    # table 4
    (4, 'addr'): 'go:webServer.addr',
    (4, 'port'): 'go:webServer.port',
    (4, 'user'): 'go:webServer.user',
    (4, 'password'): 'go:webServer.password',
    (4, 'enable_prometheus'): 'go:enablePrometheus',
    (4, 'tls_cert_file'): 'go:webServer.tls.certFile',
    (4, 'tls_key_file'): 'go:webServer.tls.keyFile',
    (4, 'custom_404_page'): 'go:custom404Page',
    (4, 'assets_dir'): 'go:webServer.assetsDir',
    (4, 'pprof_enable'): 'go:webServer.pprofEnable',
    # table 5
    (5, 'tcp_mux'): 'go:transport.tcpMux',
    (5, 'tcp_mux_keepalive_interval'): 'go:transport.tcpMuxKeepaliveInterval',
    (5, 'tcp_mux_keepalive_timeout'): 'divergent',
    (5, 'heartbeat_timeout'): 'go:transport.heartbeatTimeout',
    (5, 'tcp_keepalive'): 'go:transport.tcpKeepalive',
    # table 6
    (6, 'bind_port'): 'go:sshTunnelGateway.bindPort',
    (6, 'bind_addr'): 'extension:sshTunnelGateway.bindAddr',
    (6, 'private_key_file'): 'go:sshTunnelGateway.privateKeyFile',
    (6, 'auto_gen_private_key_path'): 'go:sshTunnelGateway.autoGenPrivateKeyPath',
    (6, 'authorized_keys_file'): 'go:sshTunnelGateway.authorizedKeysFile',
    (6, 'ssh_session_idle_timeout'): 'divergent',
    # table 7
    (7, 'name'): 'go:name',
    (7, 'url'): 'extension:url',
    (7, 'ops'): 'go:ops',
    (7, 'timeout'): 'extension:timeout',
    (7, 'enable_control'): 'extension:enableControl',
    # table 8
    (8, 'server_addr'): 'go:serverAddr',
    (8, 'server_port'): 'go:serverPort',
    (8, 'transport_protocol'): 'go:protocol',
    (8, 'token'): 'go:auth.token',
    (8, 'user'): 'go:user',
    (8, 'client_id'): 'go:clientID',
    (8, 'metas'): 'go:metadatas',
    (8, 'proxy_url'): 'go:transport.proxyURL',
    (8, 'nat_hole_stun_server'): 'go:natHoleStunServer',
    (8, 'start'): 'go:start',
    (8, 'includes'): 'go:includes',
    (8, 'tls_enable'): 'go:transport.tls.enable',
    (8, 'tls_cert_file'): 'go:transport.tls.certFile',
    (8, 'tls_key_file'): 'go:transport.tls.keyFile',
    (8, 'tls_ca_file'): 'go:transport.tls.trustedCaFile',
    (8, 'tls_server_name'): 'go:transport.tls.serverName',
    (8, 'disable_custom_tls_first_byte'): 'go:disableCustomTLSFirstByte',
    (8, 'login_fail_exit'): 'go:loginFailExit',
    (8, 'pool_count'): 'go:poolCount',
    (8, 'heartbeat_interval'): 'go:transport.heartbeatInterval',
    (8, 'dns_server'): 'go:dnsServer',
    (8, 'dial_server_keepalive'): 'go:dialServerKeepalive',
    (8, 'connect_server_local_ip'): 'go:connectServerLocalIP',
    (8, 'tcp_mux'): 'go:transport.tcpMux',
    (8, 'tcp_mux_keepalive_timeout'): 'divergent',
    (8, 'v2'): 'nontoken:`transport.wireProtocol = "v2"`',
    # table 9
    (9, 'method'): 'go:auth.method',
    (9, 'token'): 'go:auth.token',
    (9, 'token_source'): 'go:auth.tokenSource',
    (9, 'oidc_client_id'): 'go:auth.oidc.clientID',
    (9, 'oidc_client_secret'): 'go:auth.oidc.clientSecret',
    (9, 'oidc_audience'): 'go:auth.oidc.audience',
    (9, 'oidc_token_endpoint'): 'go:auth.oidc.tokenEndpointURL',
    (9, 'oidc_scope'): 'go:auth.oidc.scope',
    (9, 'oidc_issuer'): 'go:auth.oidc.issuer',
    (9, 'additional_endpoint_params'): 'go:auth.oidc.additionalEndpointParams',
    (9, 'oidc_token_source'): 'go:auth.oidc.tokenSource',
    (9, 'authentication_timeout'): 'extension:auth.authenticationTimeout',
    (9, 'oidc_tls_trusted_ca_file'): 'go:auth.oidc.trustedCaFile',
    (9, 'oidc_tls_insecure_skip_verify'): 'go:auth.oidc.insecureSkipVerify',
    (9, 'oidc_proxy_url'): 'go:auth.oidc.proxyURL',
    (9, 'additional_auth_scopes'): 'go:auth.additionalScopes',
    # table 10
    (10, 'addr'): 'go:webServer.addr',
    (10, 'port'): 'go:webServer.port',
    (10, 'user'): 'go:webServer.user',
    (10, 'password'): 'go:webServer.password',
    (10, 'enable_prometheus'): 'go:enablePrometheus',
    (10, 'tls_cert_file'): 'divergent',
    (10, 'tls_key_file'): 'divergent',
    (10, 'custom_404_page'): 'divergent',
    # table 11
    (11, 'name'): 'nontoken:**Required.**',
    (11, 'type'): 'nontoken:**Required.**',
    (11, 'local_ip'): 'go:localIP',
    (11, 'local_port'): 'go:localPort',
    (11, 'remote_port'): 'go:remotePort',
    (11, 'use_encryption'): 'go:useEncryption',
    (11, 'use_compression'): 'go:useCompression',
    (11, 'enabled'): 'go:enabled',
    # table 12
    (12, 'bandwidth_limit'): 'go:bandwidthLimit',
    (12, 'bandwidth_limit_mode'): 'go:bandwidthLimitMode',
    (12, 'group'): 'go:group',
    (12, 'group_key'): 'go:groupKey',
    (12, 'health_check_type'): 'qualified:healthCheck.type:nested',
    (12, 'health_check_url'): 'qualified:healthCheck.path:nested',
    (12, 'health_check_http_headers'): 'qualified:healthCheck.httpHeaders:nested',
    (12, 'health_check_interval_seconds'): 'qualified:healthCheck.intervalSeconds:nested',
    (12, 'health_check_timeout_seconds'): 'qualified:healthCheck.timeoutSeconds:nested',
    (12, 'health_check_max_failed'): 'qualified:healthCheck.maxFailed:nested',
    (12, 'multiplexer'): 'go:multiplexer',
    # table 13
    (13, 'custom_domains'): 'go:customDomains',
    (13, 'subdomain'): 'go:subdomain',
    (13, 'http_user'): 'go:httpUser',
    (13, 'http_password'): 'go:httpPassword',
    (13, 'http_pwd'): 'go:httpPassword',
    (13, 'host_header_rewrite'): 'go:hostHeaderRewrite',
    (13, 'headers'): 'extension:headers',
    (13, 'response_headers'): 'go:responseHeaders',
    (13, 'locations'): 'go:locations',
    (13, 'route_by_http_user'): 'go:routeByHTTPUser',
    (13, 'allow_users'): 'go:allowUsers',
    # table 14
    (14, 'sk'): 'go:secretKey',
    (14, 'virtual_net'): 'divergent',
    # table 15
    (15, 'annotations'): 'go:annotations',
    (15, 'metas'): 'go:metadatas',
    (15, 'proxy_protocol_version'): 'go:proxyProtocolVersion',
    # table 16
    (16, 'type'): 'go:type',
    (16, 'http_user'): 'go:httpUser',
    (16, 'http_password'): 'go:httpPassword',
    (16, 'local_addr'): 'go:localAddr',
    (16, 'local_path'): 'go:localPath',
    (16, 'strip_prefix'): 'go:stripPrefix',
    (16, 'host_header_rewrite'): 'go:hostHeaderRewrite',
    (16, 'username'): 'go:username',
    (16, 'password'): 'go:password',
    (16, 'crt_file'): 'go:crtPath',
    (16, 'key_file'): 'go:keyPath',
    (16, 'server_name'): 'go:serverName',
    (16, 'secret_key'): 'go:secretKey',
    (16, 'bind_addr'): 'go:bindAddr',
    (16, 'bind_port'): 'go:bindPort',
    # table 17
    (17, 'name'): 'go:name',
    (17, 'type'): 'go:type',
    (17, 'server_name'): 'go:serverName',
    (17, 'secret_key'): 'nontoken:`sk` / `secretKey`',
    (17, 'server_user'): 'go:serverUser',
    (17, 'bind_addr'): 'go:bindAddr',
    (17, 'bind_port'): 'go:bindPort',
    (17, 'plugin'): 'go:plugin',
    (17, 'fallback_timeout_ms'): 'go:fallbackTimeoutMs',
    (17, 'fallback_to'): 'go:fallbackTo',
    (17, 'disable_assisted_addrs'): 'go:disableAssistedAddrs',
    (17, 'use_encryption'): 'go:useEncryption',
    (17, 'use_compression'): 'go:useCompression',
    (17, 'protocol'): 'go:protocol',
    (17, 'keep_tunnel_open'): 'go:keepTunnelOpen',
    (17, 'max_retries_an_hour'): 'go:maxRetriesAnHour',
    (17, 'min_retry_interval'): 'go:minRetryInterval',
}

TOK = re.compile(r'^`([A-Za-z][A-Za-z0-9_.]*)`$')
QUAL = re.compile(r'^`([A-Za-z][A-Za-z0-9_.]*)`\s+\((start|end|nested)\)$')
DIVERGENT = re.compile(r'^`?—')
NONTOKEN = ('**Required.**', '`sk` / `secretKey`', '`transport.wireProtocol = "v2"`')
PINS = ((22, 'websocket_port'), (25, 'tls_enable'))
PHRASE = 'no Go server field'


def emit(kind, msg):
    sys.stdout.write('%s %s\n' % (kind, msg))


def short(text):
    text = text.replace('\n', ' ')
    if len(text) > 72:
        text = text[:69] + '...'
    return text


try:
    raw = open(sys.argv[1], encoding='utf-8').read()
except OSError as exc:
    emit('bad', 'inventory: cannot read the file under test (%s)' % exc)
    sys.exit(0)

lines = raw.split('\n')

tables = []
rows = []
i = 0
while i < len(lines):
    if lines[i].strip() == HDR:
        tables.append(i + 1)
        j = i + 2
        while j < len(lines) and lines[j].startswith('|'):
            cells = re.split(r'(?<!\\)\|', lines[j].strip().strip('|'))
            if len(cells) >= 4:
                rows.append((j + 1, len(tables), cells[0].strip(), cells[3].strip()))
            j += 1
        i = j
    else:
        i += 1

# (line, field cell, go cell, class, message, token-or-None)
classified = []
table_of = {}
for ln, table, field, cell in rows:
    table_of[ln] = table
    m = TOK.match(cell)
    if m:
        tok = m.group(1)
        if tok in GO:
            classified.append((ln, field, cell, 'go', '`%s` is a Go frp v0.71.0 json spelling' % tok, tok))
        elif tok in ALIASES:
            classified.append((ln, field, cell, 'alias',
                               '`%s` is a recorded doc spelling, not a Go frp v0.71.0 json key (%s)'
                               % (tok, ALIASES[tok]), tok))
        else:
            classified.append((ln, field, cell, 'unknown',
                               'Go cell `%s` is not a Go frp v0.71.0 json spelling, a recorded doc '
                               'alias, a divergence marker or a documented non-token shape' % short(tok), tok))
        continue
    q = QUAL.match(cell)
    if q:
        tok, shape = q.group(1), q.group(2)
        if tok in GO:
            classified.append((ln, field, cell, 'qualified',
                               'Go cell `%s` (%s) names the Go frp v0.71.0 json spelling `%s`'
                               % (tok, shape, tok), tok))
        else:
            classified.append((ln, field, cell, 'unknown',
                               'Go cell `%s` (%s) is not a Go frp v0.71.0 json spelling' % (tok, shape), tok))
        continue
    if DIVERGENT.match(cell):
        classified.append((ln, field, cell, 'divergent',
                           '%s records a divergence marker (%s)' % (field, short(cell)), None))
        continue
    if cell in NONTOKEN:
        classified.append((ln, field, cell, 'nontoken',
                           '%s carries the documented non-token shape %s' % (field, cell), None))
        continue
    classified.append((ln, field, cell, 'unknown',
                       'Go cell %s is not a Go frp v0.71.0 json spelling, a recorded doc alias, '
                       'a divergence marker or a documented non-token shape (%s)'
                       % (short(cell) if cell else '<empty>', field), None))

divergent = [c for c in classified if c[3] == 'divergent']
alias_rows = [c for c in classified if c[3] == 'alias']
alias_used = set(c[5] for c in alias_rows)


def count_check(what, got, want):
    if got == want:
        emit('ok', 'inventory: %d %s' % (got, what))
    else:
        emit('bad', 'inventory: the file under test carries %d %s, expected %d' % (got, what, want))


# --- the recorded Go key set is diffed against the embedded table -------------------
try:
    artifact_raw = open(GO_ARTIFACT, encoding='utf-8').read().split('\n')
except OSError as exc:
    artifact_raw = []
    emit('bad', 'the recorded Go key artifact cannot be read (%s): %s'
         % (exc, short(GO_ARTIFACT)))
recorded = [line.strip() for line in artifact_raw if line.strip() and not line.startswith('#')]
count_check('recorded Go key(s)', len(recorded), EXPECTED_GO_KEYS)
count_check('recorded Go dotted path(s)',
            len([k for k in recorded if '.' in k]), EXPECTED_GO_DOTTED)
count_check('recorded Go bare field name(s)',
            len([k for k in recorded if '.' not in k]), EXPECTED_GO_BARE)
if recorded and recorded == sorted(recorded) and len(set(recorded)) == len(recorded):
    emit('ok', 'the recorded Go key set is sorted and duplicate-free (byte-stable)')
else:
    emit('bad', 'the recorded Go key set is not sorted and duplicate-free — regenerate it with '
                'scripts/tests/docs-go-column-derive-go-keys.sh --write, do not hand-edit it')
if set(recorded) == GO:
    emit('ok', 'the embedded GO table matches the recorded key set (%d spellings)' % len(GO))
else:
    only_go = sorted(GO - set(recorded))
    only_art = sorted(set(recorded) - GO)
    emit('bad', 'the embedded GO table disagrees with the recorded key set (only in GO: %s; '
                'only in the artifact: %s)'
         % (', '.join('`%s`' % k for k in only_go[:4]) or '-',
            ', '.join('`%s`' % k for k in only_art[:4]) or '-'))
for needle, what in (('40adeed73b51e7ee1766d7cfb15d02ba9431ba2b', 'tag object'),
                     ('4a23aa181c1d7e28eecaa8216024ed753b9d27c8', 'commit')):
    if any(needle in line for line in artifact_raw):
        emit('ok', 'the artifact records the pinned Go %s %s' % (what, needle))
    else:
        emit('bad', 'the artifact does not record the pinned Go %s (%s)'
             % (what, needle))

count_check('Go-column table(s)', len(tables), EXPECTED_TABLES)
count_check('data row(s)', len(rows), EXPECTED_ROWS)
count_check('divergence marker row(s)', len(divergent), EXPECTED_DIVERGENT)
count_check('recorded doc-alias row(s)', len(alias_rows), EXPECTED_ALIAS_ROWS)

unused = sorted(set(ALIASES) - alias_used)
if not unused:
    emit('ok', 'inventory: all %d recorded doc-alias spelling(s) are used by the file under test' % len(ALIASES))
else:
    emit('bad', 'inventory: %d recorded doc-alias spelling(s) are unused by the file under test: %s'
         % (len(unused), ', '.join('`%s`' % u for u in unused[:6])))

count_check('recorded row mapping(s)', len(ROW_GO_PATHS), EXPECTED_ROW_PATHS)
count_check('recorded alias resolution(s)', len(ALIAS_RESOLUTION), EXPECTED_RESOLUTIONS)

# --- every alias resolution is grounded in both tables and the document -------------
doc_tokens = set(c[5] for c in classified if c[5] is not None)
for tok in sorted(ALIAS_RESOLUTION):
    res = ALIAS_RESOLUTION[tok]
    problems = []
    if tok in GO:
        problems.append('`%s` is a Go v0.71.0 key, so it needed no resolution' % tok)
    if tok in doc_tokens:
        problems.append('the document still carries `%s` as a row cell' % tok)
    if res.startswith('repoint:'):
        target = res.split(':', 1)[1]
        if target not in GO:
            problems.append('the recorded Go path `%s` is not in the key set' % target)
        if not any(e in ('go:%s' % target, 'qualified:%s' % target)
                   or e.startswith('qualified:%s:' % target)
                   for e in ROW_GO_PATHS.values()):
            problems.append('no row records `%s` as its Go path' % target)
    elif res == 'extension':
        if not any(e == 'extension:%s' % tok for e in ROW_GO_PATHS.values()):
            problems.append('no row records the extension marker for it')
    else:
        problems.append('unknown resolution %r' % res)
    if problems:
        emit('bad', 'alias `%s` (%s): %s' % (tok, res, '; '.join(problems)))
    else:
        emit('ok', 'alias `%s` is resolved (%s)' % (tok, res))


def expected_failure(exp, cell, tok):
    """None when `cell` is the recorded cell for `exp`; else why it is not."""
    if exp.startswith('go:'):
        want = exp[3:]
        if want not in GO:
            return 'its recorded Go path `%s` is not in the key set' % want
        if cell != '`%s`' % want:
            return 'expected the recorded Go path `%s`, found %s' % (want, short(cell))
        return None
    if exp.startswith('qualified:'):
        want, shape = exp[len('qualified:'):].split(':')
        q = QUAL.match(cell)
        if want not in GO:
            return 'its recorded Go path `%s` is not in the key set' % want
        if q is None or q.group(1) != want or q.group(2) != shape:
            return 'expected the recorded Go path `%s` (%s), found %s' % (want, shape, short(cell))
        return None
    if exp.startswith('extension:'):
        spelling = exp[len('extension:'):]
        if spelling in GO:
            return 'the recorded extension spelling `%s` is a Go v0.71.0 key' % spelling
        if not DIVERGENT.match(cell):
            return 'expected a divergence marker naming `%s`, found %s' % (spelling, short(cell))
        if spelling not in cell:
            return 'the divergence marker does not name the absent spelling `%s`' % spelling
        return None
    if exp == 'divergent':
        if not DIVERGENT.match(cell):
            return 'expected a divergence marker, found %s' % short(cell)
        return None
    if exp.startswith('nontoken:'):
        want = exp[len('nontoken:'):]
        if cell != want:
            return 'expected the documented non-token shape %s, found %s' % (short(want), short(cell))
        return None
    if exp.startswith('alias:'):
        want = exp[len('alias:'):]
        if want not in ALIASES:
            return 'its recorded alias `%s` is not in the accepted ALIASES table' % want
        if cell != '`%s`' % want:
            return 'expected the recorded alias `%s`, found %s' % (want, short(cell))
        return None
    return 'unknown recorded expectation %r' % exp


seen_rows = set()
for ln, field, cell, cls, msg, tok in classified:
    if cls == 'unknown':
        emit('bad', 'docs/config.md:%d %s' % (ln, msg))
        continue
    key = (table_of[ln], field.strip('`'))
    exp = ROW_GO_PATHS.get(key)
    if exp is None:
        emit('bad', 'docs/config.md:%d row %s has no recorded Go mapping in ROW_GO_PATHS '
                    '(expected path, qualified path, divergence marker or non-token shape)'
             % (ln, field))
        continue
    seen_rows.add(key)
    why = expected_failure(exp, cell, tok)
    if why:
        emit('bad', 'docs/config.md:%d row %s: %s' % (ln, field, why))
    else:
        emit('ok', 'docs/config.md:%d %s' % (ln, msg))

unused_rows = sorted(k for k in ROW_GO_PATHS if k not in seen_rows)
if not unused_rows:
    emit('ok', 'inventory: all %d recorded row mapping(s) are used by the file under test'
         % len(ROW_GO_PATHS))
else:
    emit('bad', 'inventory: %d recorded row mapping(s) are unused by the file under test: %s'
         % (len(unused_rows), ', '.join('table %d %s' % k for k in unused_rows[:6])))

by_line = dict((c[0], c) for c in classified)
for ln, field in PINS:
    want_field = '`%s`' % field
    c = by_line.get(ln)
    if c is None:
        emit('bad', 'docs/config.md:%d pinned row %s is absent from the file under test' % (ln, field))
    elif c[1] != want_field:
        emit('bad', 'docs/config.md:%d pinned row %s is at a different line (found %s)'
             % (ln, field, short(c[1])))
    elif c[3] != 'divergent' or PHRASE not in c[2]:
        emit('bad', 'docs/config.md:%d pinned row %s no longer records the "%s" divergence marker '
                    '(Go cell: %s)' % (ln, field, PHRASE, short(c[2])))
    else:
        emit('ok', 'docs/config.md:%d pinned row %s records the "%s" divergence marker'
             % (ln, field, PHRASE))
PY
}

# --- scenario 2: mutate a throwaway copy of the Go cell on a given line -------
mutate_go_cell() { # <src> <dst> <line> <new-go-cell>
  python3 -B - "$1" "$2" "$3" "$4" <<'PY'
import re
import sys

src, dst, ln, new = sys.argv[1], sys.argv[2], int(sys.argv[3]), sys.argv[4]
lines = open(src, encoding='utf-8').read().split('\n')
cells = re.split(r'(?<!\\)\|', lines[ln - 1].strip().strip('|'))
cells[3] = ' ' + new + ' '
lines[ln - 1] = '|' + '|'.join(cells) + '|'
open(dst, 'w', encoding='utf-8').write('\n'.join(lines))
PY
}

expect_red() { # <name> <doc> <needle> <needle>
  local name=$1 doc=$2 first=$3 second=$4 out
  out="$(scan "$doc")"
  if printf '%s\n' "$out" | grep -Fq "$first" && printf '%s\n' "$out" | grep -Fq "$second"; then
    ok "$name"
  else
    bad "$name — the mutant did not red as expected (want '$first' + '$second'); the check would be vacuous"
  fi
}

# --- scenario 1: the scan of $DOCS_CONFIG ------------------------------------
report="$(scan "$DOCS_CONFIG")"
while IFS= read -r line; do
  case "$line" in
    "ok "*) ok "${line#ok }" ;;
    "bad "*) bad "${line#bad }" ;;
  esac
done <<<"$report"

# --- scenario 2: each mutation must red --------------------------------------
M1="$WORK/m1.md"
if mutate_go_cell "$PRISTINE" "$M1" 22 '`websocketPort`' && grep -Fq '`websocketPort`' "$M1"; then
  expect_red 'M1 (websocket_port reworded to the Go spelling `websocketPort`): docs/config.md:22 reds' \
    "$M1" 'bad docs/config.md:22' '`websocketPort` is not a Go frp v0.71.0'
else
  bad 'M1 mutation did not apply — anchor missing, the check would be vacuous'
fi

M2="$WORK/m2.md"
if mutate_go_cell "$PRISTINE" "$M2" 25 '`tlsEnable`' && grep -Fq '`tlsEnable`' "$M2"; then
  expect_red 'M2 (tls_enable reworded to the Go spelling `tlsEnable`): docs/config.md:25 reds' \
    "$M2" 'bad docs/config.md:25' '`tlsEnable` is not a Go frp v0.71.0'
else
  bad 'M2 mutation did not apply — anchor missing, the check would be vacuous'
fi

M3="$WORK/m3.md"
if mutate_go_cell "$PRISTINE" "$M3" 14 '`bindAddress`' && grep -Fq '`bindAddress`' "$M3"; then
  expect_red 'M3 (a curated token misspelled, `bindAddr` -> `bindAddress`): docs/config.md:14 reds' \
    "$M3" 'bad docs/config.md:14' '`bindAddress` is not a Go frp v0.71.0'
else
  bad 'M3 mutation did not apply — anchor missing, the check would be vacuous'
fi

M4="$WORK/m4.md"
printf '# Configuration Reference\n\nNo tables here.\n' >"$M4"
expect_red 'M4 (every Go-column table dropped): the row floor reds' \
  "$M4" 'bad inventory:' '0 Go-column table(s)'

M5="$WORK/m5.md"
if mutate_go_cell "$PRISTINE" "$M5" 22 '—' && grep -Fq '| — |' "$M5"; then
  expect_red "M5 (websocket_port's divergence prose stripped): the pinned row reds" \
    "$M5" 'bad docs/config.md:22' 'no longer records'
else
  bad 'M5 mutation did not apply — anchor missing, the check would be vacuous'
fi

M6="$WORK/m6.md"
if mutate_go_cell "$PRISTINE" "$M6" 15 '`quicBindPort`' && grep -Fq '`quicBindPort`' "$M6"; then
  expect_red 'M6 (a real but wrong Go key swapped into `bind_port`, `bindPort` -> `quicBindPort`): docs/config.md:15 reds the row mapping' \
    "$M6" 'bad docs/config.md:15' 'expected the recorded Go path `bindPort`'
else
  bad 'M6 mutation did not apply — anchor missing, the check would be vacuous'
fi

M7="$WORK/m7.md"
if mutate_go_cell "$PRISTINE" "$M7" 15 '`kcpPort`' && grep -Fq '`kcpPort`' "$M7"; then
  expect_red 'M7 (`kcpPort` is not a Go v0.71.0 spelling): docs/config.md:15 reds membership' \
    "$M7" 'bad docs/config.md:15' '`kcpPort` is not a Go frp v0.71.0'
else
  bad 'M7 mutation did not apply — anchor missing, the check would be vacuous'
fi

# ---------------------------------------------------------------- summary
printf '\n'
if [ "$fails" -eq 0 ]; then
  printf 'RESULT: %d fixture check(s) hold\n' "$checks"
  exit 0
fi
printf 'RESULT: %d fixture check(s), %d failure(s) above\n' "$checks" "$fails"
exit 1
